[[pages]]
path = "app.py"
name = "ğŸ  Strona gÅ‚Ã³wna"
icon = "ğŸ "

[[pages]]
path = "pages/1_pobieranie_okladek.py"
name = "ğŸ“¥ Pobieranie okÅ‚adek"
icon = "ğŸ“¥"

[[pages]]
path = "pages/2_zmiana_opisu_html.py"
name = "ğŸ“ Konwerter HTML"
icon = "ğŸ“"

[[pages]]
path = "pages/3_konwerter_webp.py"
name = "ğŸ–¼ï¸ Konwerter obrazÃ³w"
icon = "ğŸ–¼ï¸"